repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 581213484f4262600d17c71e272176d4eb6724a5  # frozen: v1.109.0
    hooks:
      - id: terraform_fmt
        args:
          # renovate: datasource=github-releases depName=hashicorp/terraform
          - --hook-config=--tool-version=1.5.7

